env0/terraform-provider-env0

.github/workflows/release.yml, .goreleaser.yml
Following instructions in Terraform Registry - Publishing Providers - Terraform by HashiCorp https://www.terraform.io/docs/registry/providers/publishing.html
In order to support releasing the provider to the public Terraform Registry 
Is being done for #5
=> Adding configs for auto release 

client/model.go, env0/data_template.go, env0/resource_template.go, examples/004_template/conf.tf, examples/004_template/main.tf
Added Terraform version to template 
set default terraform version =  0.15.1
added to data and resource 
updated template test with tf version
=> Added Terraform version

env0/data_organization.go, env0/data_organization_test.go, env0/test_helpers.go
=> Chore: Add organization data tests

client/api_client.go, client/api_client_mock.go, client/cloud_credentials_project_assignment.go, client/cloud_credentials_project_assignment_test.go, client/http/client_mock.go, client/organization_test.go, env0/resource_template_project_assignment.go
Help #72 with tests
add ut for `client/cloud_credentials_project_assignment.go`
Update the `client/cloud_credentials_project_assignment.go` to the new api of env0
=> Add tests for Credentials to project assignment

env0/data_configuration_variable_test.go
=> Chore: UT: data - Configuration Variable - tests

README.md
Added instructions to the readme on how to install `mockgen` properly.
=> Chore: Update readme - installing mockgen

.github/workflows/integration-tests.yml
Add integration tests CI
Add integration tests CI
=> Feat: Add integration tests CI

client/api_client.go, client/api_client_mock.go, client/model.go, client/notification.go, client/notification_test.go, env0/data_notification.go, env0/resource_module.go, env0/resource_notification.go, env0/resource_notification_test.go, env0/utils.go, env0/utils_test.go
This is the first part of fixing #280. This PR refactors the notification resource a little bit.
=> Feat: refactor notification resource code (#280)

examples/resources/env0_notification/resource.tf, tests/integration/017_notification/main.tf
resolves #280 
The last PR for adding support for notifications and notification assignments to projects.
=> Feat: added documentation and integration tests

env0/resource_team.go, env0/resource_team_test.go
Added a fix for teams resource.
Part of #284 .
=> Fix: handle drift in all resources

client/api_client.go, client/api_client_mock.go, client/api_key.go, client/api_key_test.go, client/cloud_credentials.go, client/cloud_credentials_test.go, client/model.go, env0/data_aws_credentials.go, env0/data_aws_credentials_test.go, env0/data_azure_credentials.go, env0/data_azure_credentials_test.go, env0/data_gcp_credentials.go, env0/data_gcp_credentials_test.go, env0/resource_aws_credentials_test.go, env0/resource_azure_credentials_test.go, env0/resource_gcp_credentials_test.go
Implement api-keys API client calls.
=> Feat: add support for API key resource

env0/data_project.go, env0/errors.go, env0/provider.go, env0/resource_aws_credentials.go, env0/resource_azure_credentials.go, env0/resource_configuration_variable.go, env0/resource_configuration_variable_test.go, env0/resource_gcp_credentials.go, env0/resource_git_token.go, env0/resource_git_token_test.go, env0/resource_module.go, env0/resource_module_test.go, env0/resource_notification_project_assignment.go, env0/resource_team.go
Some minor refactoring to increase code reusability.
Added the resource git token.
Part of #148.
=> Feat: add git token resource

client/model.go, env0/provider.go, env0/resource_api_key.go, env0/resource_api_key_test.go, env0/resource_notification.go
Implemented the resource and added unit tests.
Part of #281
=> Feat: add the api key resource

DEVELOPMENT.md
closes #206 
Added the first version of DEVELOPMENT.md that explains a bit about creating a new resource/data.
=> Chore: add README that explains how to create a new resource/data

env0/resource_environment.go
#closes #328
Added an if to check if it's an acceptance test or not. If it's not an acceptance test: sleep. If it's an acceptance test: don't sleep.
=> Chore: don't sleep during acceptance tests

.goreleaser.yml
Update .goreleaser.yaml to generate changelog.
Part of #324
=> Chore: add proper release drafts

env0/resource_project_policy.go
chore(docs): update from 0 to null
=> Chore: update docs from 0 to null

client/api_client.go, client/api_client_mock.go, client/user.go, client/user_test.go, env0/data_user.go, env0/data_user_test.go, env0/provider.go, examples/data-sources/env0_user/data-source.tf
closes #298 
Added the required data source, client API, unit tests and documentation.
Note: I tested integration manually. Since the user is not known in advance, I decided not to add an integration test for it.
Note2: as requested - I'm exposing just the user id, if more fields are required please let me know.
=> Feat: add data source user

env0/data_template.go, env0/data_template_test.go
resolves #352 
Added some of the missing fields.
Updated the acceptance test.
=> Feat: data env0_template missing fields

client/api_key.go, env0/resource_api_key.go, env0/resource_api_key_test.go
Added the new field to the schema and updated the acceptance tests.
This is part of #405 (more PRs to come once this is merged).
=> Feat: support Non-Admin API key creation

client/api_client.go, client/api_client_mock.go, client/cloud_credentials.go, client/cloud_credentials_test.go, env0/resource_aws_credentials.go, env0/resource_aws_credentials_test.go, env0/resource_azure_credentials.go, env0/resource_azure_credentials_test.go, env0/resource_cost_credentials.go, env0/resource_cost_credentials_test.go, env0/resource_gcp_credentials.go, env0/resource_gcp_credentials_test.go
Moved some common API calls to use the same code.
Part of #394
=> Chore: refactor credentials and cost

env0/resource_environment.go
Added a deprecation message to the wait_for.
Part of #424
=> Chore: deprecate wait_for

client/project_policy.go, env0/data_project_policy_test.go, env0/resource_project_policy.go, env0/resource_project_policy_test.go, tests/integration/011_policy/main.tf
resolves #418 
Added the new fields and updated the tests.
Fixed some observed bugs.
=> Feat: support TTL settings in project policies

client/template.go, env0/data_source_code_variables_test.go, env0/data_template.go, env0/resource_template.go, env0/resource_template_test.go, env0/templates.go, env0/utils.go, env0/utils_test.go
Some required refactoring for supporting templateless environment.
Part of #374.
=> Feat: environment resource does not support new templateless creation

DEVELOPMENT.md, client/template.go, env0/resource_template.go, env0/resource_template_test.go, env0/templates.go
resolves #441 
Added file_name field.
Allowed "cloudformation" as a valid type.
Updated unit tests.
=> Feat: support newly added template type - cloudformation

client/template.go, env0/resource_template_test.go, env0/templates.go, go.mod, go.sum
resolves #438 
1. added the new boolean flag.
2. added unit tests.
3. added semver to go.mod for comparing versions.
=> Feat: add run-all support

env0/data_ip_ranges.go, env0/data_ip_ranges_test.go, env0/provider.go, examples/data-sources/env0_ip_ranges/data-source.tf
resolves #452 
Added the new datasource.
Implemented acceptance test.
Added example.
=> Feat: data source to publish IP ranges used by env0

client/api_key.go, env0/resource_api_key.go, env0/resource_api_key_test.go, tests/integration/020_api_key/expected_outputs.json, tests/integration/020_api_key/main.tf, tests/integration/021_teams/main.tf
resolves #460 
Added api_key_secret to the resource.
I also added omit_api_key_secret boolean for security (in case someone wants to omit the secret for the state).
Updated and added some acceptance tests and integration tests.
=> Feat: getting API_Secret from env0_api_key resources

env0/resource_configuration_variable.go, env0/resource_environment.go, env0/resource_environment_test.go
resolves #472 
Added the missing fields and updated acceptance tests.
=> Feat: the environment configuration section is missing some attributes

client/organization.go, env0/data_organization_test.go
resolves #480 
Modified to use IsSelfHostedK8s instead of IsSelfHosted.
Updated acceptance test.
=> Feat: fix is_self_hosted attribute of organization resource

tests/integration/002_project/main.tf, tests/integration/003_configuration_variable/main.tf, tests/integration/005_ssh_key/expected_outputs.json, tests/integration/005_ssh_key/main.tf, tests/integration/006_aws_credentials/expected_outputs.json, tests/integration/006_aws_credentials/main.tf, tests/integration/007_template_project_assignment/main.tf, tests/integration/008_cloud_credentials_project_assignment/main.tf, tests/integration/010_team_project_assignment/main.tf, tests/integration/011_policy/main.tf, tests/integration/013_downstream_environments/main.tf, tests/integration/014_environment_scheduling/main.tf, tests/integration/016_azure_credentials/expected_outputs.json, tests/integration/016_azure_credentials/main.tf, tests/integration/019_git_token/main.tf, tests/integration/024_cloud_credentials/expected_outputs.json, tests/integration/024_cloud_credentials/main.tf
fixes #483 
Updated the integration tests.
=> Fix: make sure all resource names are unique in integration tests

client/configuration_variable.go, env0/resource_environment.go, env0/resource_environment_test.go
Found a few bugs that may cause the issue observed.
May resolve the issue described in #459
=> Fix: diff issues with environment configuration variables

env0/resource_organization_policy.go
=> Feat: support OIDC organization policy settings

client/api_client.go, client/api_client_mock.go, client/role.go, client/role_test.go, client/team_project_assignment.go, client/user_project_assignment.go, env0/validators.go
Part of #498 
Implements client calls for roles + unit tests.
=> Feat: new custom role resource

client/project_policy.go, env0/resource_project_policy.go, env0/resource_project_policy_test.go, env0/utils.go, tests/integration/011_policy/main.tf
Fixes #524 
Fixed a few issues (see in comments), and tested manually.
=> Fix: unable to set max environments in projects

env0/resource_custom_role.go
fixes #532 
Added the missing permissions.
=> Fix: custom role permissions missing

env0/data_custom_role.go, env0/data_custom_role_test.go, env0/provider.go, examples/data-sources/env0_custom_role/data-source.tf, tests/integration/010_team_project_assignment/main.tf
resolves #534 
1. Added the data source.
2. Added acceptance tests.
3. Added integration tests.
4. Added examples.
=> Feat: add data source for getting custom role

client/module.go, client/module_test.go, env0/resource_module.go, env0/resource_module_test.go, tests/integration/018_module/main.tf
resolves #554 
1. Added "path" to the schema and API calls.
2. Updated API tests.
3. Updated acceptance tests.
4. Updated integration tests.
=> Feat: support module registry from path

env0/provider.go
resolves #556 
Enabled the retry mechanism and added conditions for retrying: network error and 5xx.
Note: Integration tests will be used to validate this change. The benefit of adding unit/acceptance tests for this is low (no point in testing "rest")
=> Feat: provider should retry API requests

client/api_client.go, client/api_client_mock.go, client/custom_flow.go, client/custom_flow_test.go, client/http/client.go
Part of the effort to add custom flow support #550 
In this PR I implemented the assignment API calls and added unit tests.
=> Feat: custom flow support

env0/resource_environment.go
Part of the effort to add support for subenvironments #536.
In this PR I defined the schema.
=> Feat: add support for subenvironments

env0/provider.go
=> Feat: add logs to retry of harness tests

client/environment.go, env0/resource_environment.go, env0/resource_environment_test.go, tests/integration/012_environment/main.tf
resolves #576 
1. Added is_inactive to the schema.
3. Updated integration tests.
=> Feat: able to define is_archived at env0_environment resources

env0/provider.go
fixes #584 
Added a retry in case "[]" is returned during integration testing.
=> Fix: resolve flaky integration tests for list*** api calls

env0/resource_aws_credentials.go, env0/resource_azure_credentials.go, env0/resource_gcp_credentials.go
=> Chore: better docs for secret reference usage in credentials on self-hosted organizations

README.md
Adding instruction on how to create a template or VCS environment from provider using the master environment
Write it.
=> Chore: updating README with creating template/VCS environment using master environment

env0/provider.go
Modified from "INFO" to "WARN".
Added another print message.
=> Chore: change info level to warn level

go.mod, go.sum
Upgraded libraries for security issues reported by dependenbot.
=> Chore: upgrade libraries for security issues

env0/resource_custom_role.go
resolves #601 
added 3 new permissions to the custom roles.
=> Feat: add new permission to custom role resource

client/cloud_credentials.go, go.sum
=> Fix: external_id is sent empty - causes 400 error

env0/resource_custom_role.go, tests/integration/026_custom_role/main.tf
fixes #618 
1. Fixed the "typo".
2. Updated the integration test.
=> Fix: custom roles contain a wrong permission MANAGE_BILLINGS

env0/provider.go, env0/resource_workflow_trigger.go, env0/resource_workflow_trigger_test.go, env0/resource_workflow_triggers.go, env0/resource_workflow_triggers_test.go, examples/resources/env0_workflow_trigger/resource.tf, tests/integration/013_downstream_environments/main.tf
resolves #580 
1. added the resource.
2. added acceptance tests.
3. added integration tests.
4. added an example.
=> Feat: workflow trigger new resources

env0/provider.go
resolves #631 
Checks for organization id environment variable (over the setting in the provider).
=> Feat: add support for Organization ID as an Environment variable

env0/data_project.go, env0/data_project_test.go, env0/resource_project.go, tests/integration/002_project/main.tf
resolves #630 
1. Added the new filter to schema.
2. Added acceptance tests.
3. Added integration tests.
=> Feat: ability to filter for parent project name in data project resource

client/project_policy.go, env0/data_project_policy.go, env0/data_project_policy_test.go, env0/resource_project_policy.go, env0/resource_project_policy_test.go
resolves #650 
1. Added the new field to the API.
2. Added the new field to the resource schema.
3. Added the new field to the data schema.
4. Updated the acceptance tests.
=> Feat: add support for force env0 remote backend project policy

client/environment.go, env0/resource_drift_detection.go, env0/resource_environment.go, env0/resource_environment_test.go, tests/integration/012_environment/main.tf
resolves #664 
1. Added a new drift_detection_cron field to the environment schema and implemented create and update use-cases.
3. Updated integration tests.
=> Feat: add support for drift detection creation for environment resource

env0/data_template.go, tests/harness.go, tests/integration/021_teams/main.tf, tests/integration/022_templates/expected_outputs.json, tests/integration/022_templates/main.tf
closes #657 
1. reverted the revert.
2. updated the integration tests to avoid race conditions.
=> Feat: run harness parallel tests in parallel

client/environment.go, env0/resource_environment.go, env0/resource_environment_test.go
fixes #680 
Found multiple (old) bugs in environment resource.
There was no acceptance test for import. Once I added the acceptance test I noticed all the issues.
1. Fixed bugs.
2. Updated acceptance test.
=> Fix: env0_environment import missing some fields

env0/provider.go
fixes #695 
Updated the code to avoid nil pointer crashes.
=> Fix: plugin v1.4.14 crashes

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Chore: add an issue template for reporting different types of issues

client/api_client.go, client/api_client_mock.go, client/project_budget.go, client/project_budget_test.go
The first part for adding project budget resource support.
This PR adds the API calls and unit tests.
=> Feat: budget resource for project

client/project_budget.go, env0/provider.go, env0/resource_project_budget.go, env0/resource_project_budget_test.go, env0/test_helpers.go, env0/utils.go, examples/resources/env0_project_budget/resource.tf, tests/integration/002_project/main.tf
resolves #703 
1. Added the new resource schema.
2. Added acceptance tests.
3. Added integration tests.
4. Added an example.
5. Added support for slice of ints.
=> Feat: Budget Resource (for project)

env0/resource_custom_role.go
fixes #728 
Added 4 new custom roles.
=> Fix: missing CUSTOM_ROLE roles

env0/provider.go
"Received respose" -> "Received response"
=> Fix: typo in provider.tf

go.mod, go.sum
resolves #779 
Updated restry from 2.10.0 to 2.11.0.
=> Fix: resty race condition sending body twice

client/notification.go, env0/resource_notification.go, tests/integration/017_notification/main.tf
resolves #795 
1. Updated the schema to accept Email type.
2. Added the use-case to the integration test.
=> Feat: add email notification support to the schema

env0/resource_configuration_variable.go
closes #798 
The code aligns with the API. Therefore, I did not modify the code.
Instead, I've updated the documentation.
=> Fix: string is not an available format for env0_configuration_variable

docs/resources/team_project_assignment.md
=> Fix: replaced project_example with test_project like created in the example

env0/resource_team_environment_assignment.go, env0/resource_team_organization_assignment.go, examples/resources/env0_team_environment_assignment/resource.tf, examples/resources/env0_team_organization_assignment/resource.tf
resolves #816 
Updated examples and documentation.
=> Feat: document team assignments with built-in roles

env0/resource_template.go, env0/resource_template_test.go, tests/integration/005_ssh_key/main.tf, tests/integration/007_template_project_assignment/main.tf
fixes #825 
removed default terraform version.
=> Feat: remove default terraform_version

client/environment.go
update 'SubEnvironment' json from 'workspace' to 'workspaceName'
=> Fix: update 'SubEnvironment' json from 'workspace' to 'workspaceName'

client/configuration_variable.go
=> Fix: apply a mitigation for worflowEnvironmentId removed

client/notification.go, env0/resource_notification.go, env0/resource_notification_test.go, tests/integration/025_notifications/main.tf
Part of #850 
Fixed the integration test from "Slack" to "Webhook".
=> Feat: fix the integration test

client/configuration_variable.go
fixes #838 
Scope needs to be workflow and not environment.
=> Fix: configuration Variable in Workflow drift

client/environment.go
fixes #879 
JSON was sent incorrectly. Fixed it.
=> Fix: fix k8s_namespace drift

env0/resource_custom_role.go
resolves #885 
Added the new 'enum' to the list of roles.
=> Feat: support the permission EDIT_VCS_ENVIRONMENT

client/template.go, env0/resource_template_test.go, tests/integration/004_template/main.tf
fixes #916 
1. Added gitlabProjectId to template response.
2. Fixed acceptance tests.
=> Feat: gitlab_project_id always shows drift 

env0/resource_environment.go, env0/resource_environment_test.go, env0/resource_variable_set_assignment.go
fixes #919 
1. Fixed case sensitivity comparison issues.
2. Updated tests.
=> Feat: drift in variable_sets of environment resource in every plan

README.md
Make the README a tiny bit clearer, 
so unfamiliar devs won't miss approving the release action
=> Chore: Update README.md to note that the release action needs to get approved

tests/integration/003_configuration_variable/main.tf
we had a flaky waiting for the data to update increasing the timeout added at #884 
increasing the timeout
=> Fix: increase sleep time to avoid flaky test

.gitignore, client/api_client.go, client/api_client_mock.go, client/organization.go, client/organization_test.go, env0/provider.go, env0/resource_organization.go, env0/resource_organization_test.go, examples/resources/env0_organization/resource.tf
resolves #1012 
1. Add new API calls.
2. Added unit tests for new API calls.
3. Added new resource.
4. Added acceptance tests for new resource.
5. Added an example.
Did not add a harness test for creating an organization! There's no option to delete an organization.
=> Feat: env0 Organization creation via provider

env0/resource_custom_role.go
resolves #1030 
1. Removed schema validation.
2. Updated docs.
=> Chore: update docs env0_custom_role and remove schema validation

.github/workflows/ci.yml, .github/workflows/pr-approve-labeler.yml, .github/workflows/pr-auto-assign.yml, .github/workflows/pr-labeler.yml, .github/workflows/pr-validation.yml, env0/provider.go, env0/provider_test.go
=> Feat: Honor Rate Limits #2

env0/resource_environment_discovery_configuration.go
resolves #1048
Add it to the validator
=> Fix: Add resolve from code to opentofu version
