env0/terraform-provider-env0

.github/workflows/release-drafter.yml

We were missing the action workflow to trigger release drafter on merges to `main`

Add release drafter GH Action

---

go.mod
go.sum

- Our CI tests were failing , printing `unsupported state format version: expected "0.1", got "0.2"`
- Search for it in google
- See a closed issue in [terratest](https://github.com/gruntwork-io/terratest/issues/943)
- Add  indirect dependency:  `	github.com/hashicorp/terraform-json v0.12.0 // indirect` to `go.mod`
- Run `go get -v -t ./... `
- Say good shabbat.

Fix: Terraform CI Unit Tests.

---

env0/resource_team_project_assignment.go

While QAing #140 , @RLRabinowitz notice that on PR-Plan we don't validate the role.
validate it.

Fix: Validate project_role

---

client/model.go
docs/data-sources/project_policy.md
docs/resources/project_policy.md
env0/data_project_policy.go
env0/data_project_policy_test.go
env0/resource_project_policy.go
env0/resource_project_policy_test.go

…w Environments
Add ability to set default CD and PR plan by project policy
Add ability to set default CD and PR plan by project policy

feat:Ability to choose default setting for Deployment Triggers for new Environments

---

env0/resource_environment.go
env0/resource_environment_test.go

Environment resource doesn't create custom workspace name
Add workspace to create environment payload 
This PR doesn't contain UT, will be added in other PR

Fix: set workspace in environment create

---

client/api_client.go
client/api_client_mock.go
client/model.go
client/notification_project_assignment.go
client/notification_project_assignment_test.go

This PR adds the http client functionality for assigning notifications to projects.
Part of #280 (more PRs to follow).

Feat: implement notification assignments for http client

---

env0/resource_configuration_variable.go
env0/resource_configuration_variable_test.go

fixes #278 
If 404 is returned sets the configuration id to an empty string.
Added a test for the use case.

Fix: handle drift in configuration variables

---

env0/resource_aws_credentials.go
env0/resource_aws_credentials_test.go
env0/resource_azure_credentials.go
env0/resource_azure_credentials_test.go
env0/resource_gcp_credentials.go
env0/resource_gcp_credentials_test.go

Added drift handling for AWS, Azure, and GCP credentials resources.
Part of #284.

Fix: handle drift in all resources

---

client/agent_project_assignment.go
client/agent_project_assignment_test.go
client/api_client.go
client/api_client_mock.go

Part of #316 
Added the API calls and unit tests.

Feat: add support for agent settings

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
README.md
examples/resources/env0_agent_project_assignment/resource.tf
go.mod
tests/integration/002_project/main.tf

resolves #336 
Located all the 1.16 locations and modified them to 1.18.
Ran: `go mod tidy`.
(Unrelated) Formatted some terraform file (`terraform fmt`).

Feat: upgrade to go version 1.18

---

examples/provider/provider.tf
templates/index.md.tmpl

Silly me thought that on #349 I can simply edit the markdown files
Do it like https://github.com/hashicorp/terraform-plugin-docs expects (adding a template file)

Chore: main page documentation

---

env0/resource_configuration_variable.go

This does not solve the issue (I will keep the issue open and un-assign it from myself).
Instead, I deprecated the environment_id field.
```
Terraform will perform the following actions:
+ resource "env0_configuration_variable" "issue" {
+ environment_id = "4d60cf52-847d-49f3-a018-4f74ecee5dc8"
+ id             = (known after apply)
+ is_read_only   = false
+ is_required    = false
+ is_sensitive   = false
+ name           = "POOOOO"
+ type           = "environment"
+ value          = (sensitive value)
}
Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Attribute is deprecated
│ 
│   with env0_configuration_variable.issue,
│   on main.tf line 52, in resource "env0_configuration_variable" "issue":
│   52:   environment_id = env0_environment.example.id
│ 
│ use "configuration" field …
```

Fix: deprecate environment_id field

---

DEVELOPMENT.md
client/cloud_credentials.go
client/errors.go
env0/credentials.go
env0/data_notification.go
env0/errors.go
env0/resource_agent_project_assignment.go
env0/resource_api_key.go
env0/resource_aws_credentials.go
env0/resource_aws_credentials_test.go
env0/resource_git_token.go
env0/resource_module.go
env0/resource_notification.go
env0/resource_notification_project_assignment.go
env0/resource_organization_policy.go
env0/utils.go
env0/utils_test.go
examples/resources/env0_aws_credentials/import.sh

I'm keeping open, to adding support for other credential types.
Added import.
Removed a schema requirements and instead enforce during read.
Added acceptance tests.
Added a "resource" tag.
Added import examples.
Fixed some other issues I noticed.

Fix: env0_aws_credentials - apply after import will delete+create

---

env0/resource_azure_credentials.go
env0/resource_azure_credentials_test.go
examples/resources/env0_azure_credentials/import.sh

Part of a larger effort to add import to all credentials types.
This one is for Azure (AWS complete and GCP pending).
1. Fixed some bugs.
2. Added import functionality.
3. Added acceptance testing.
4. Added examples for import.

Fix: env0_azure_credentials - apply after import will delete+create

---

env0/resource_gcp_credentials.go
env0/resource_gcp_credentials_test.go
examples/resources/env0_gcp_credentials/import.sh

fixes #99 
The last part of the effort to add import to all credential types (Azure and AWS is complete).
1. Added import.
2. Fixed some bugs.
3. Added acceptance tests.
4. Added examples.

Fix: env0_gcp_credentials - apply after import will delete+create

---

.github/workflows/ci.yml
client/pagination.go

closes #415
Harness was running in go1.17 because the terraform docker image was using golang 1.17.
Switched to using a go1.18 docker image and installed terraform via `apk`.
Making this change allows me to use generics (A new feature in go1.18).

Chore: use generics in pagination

---

client/api_key.go
env0/resource_api_key.go
env0/resource_api_key_test.go
tests/integration/020_api_key/main.tf

Updated the creation call.
Added some integration and acceptance tests for "User" permissions.
Part of #405

Feat: support Non-Admin API key creation

---

env0/resource_template.go
env0/resource_template_test.go
env0/templates.go
env0/validators.go

This is a large/complex change. The feature will be divided into small PRs.
In this PR I've moved the template schema to a common function that receives template type (shared vs single).
part of #374

Feat: environment resource does not support new templateless creation

---

env0/resource_configuration_variable.go

resolves : #347 
Since Zip doesn't use `environment.configuration` but only `configuration` with environment scope, a solution for using both is irrelevant.
There was a misunderstanding regarding their usage but eventually, we decided to update the docs by describing that using `configuration.environment_id` requires `ignoring changes` of `environment.configuration`
The issue with allowing both is that `configuration` requires an environment, so at the first run, the environment will be deployed without configuration variables. From the 2nd deployment, there will be a drift because the configuration resource metadata will be retrieved by the API of the environment.
In other words, those are 2 ways to manage the same resource so only one way should be picked. ( preferably the …

Chore: Update configuration.environmentId docs

---

env0/data_template.go
env0/resource_template_test.go
env0/templates.go

resolves #425 
Added the new types to the schema (resource and data) + documentation.

Feat: support newly added template types - pulumi, k8s & workflow

---

client/template.go
client/template_test.go
env0/resource_template.go
env0/resource_template_test.go

Some refactoring I wanted to do before working on #438.
(Instead of having one large PR).
Schema validation was moved to the correct place, instead of doing it before the API call.
Updated tests accordingly.

Feat: refactoring for adding run-all support

---

client/notification_test.go
client/organization.go

fixes #448 
1. organizationId now returns error on failure.
2. Added a test that verified the use-case.

Fix: organizationId() hides the errors

---

client/environment.go
env0/resource_environment.go
env0/resource_environment_test.go

fixes #471 
Using GetOkExist.
Updarted unit tests.
The bug was that HasChange behaves the same for field not set and false.
The only way around it is to use GetOkExist. The supports: true, false, and unset. (All 3 modes are required).

Fix: CD and PR plan settings on environment are not applied correctly

---

tests/integration/018_module/main.tf

Integration tests might fail due to having a non-random env0 module resource name
Randomize it

Fix: TF module name uniqueness in integration tests

---

client/http/client.go
client/http/client_test.go

We're seeing an elevated rate of throttling errors  in the `tf_provder` tests as we do not benefit from cache when using user/password.
Use user/password once to obtain JWT and use that on following API calls.

Fix - 401 errors from auth0 sue to cache misses when using user/pass

---

client/module.go
env0/resource_organization_policy_test.go
env0/utils.go

resolves #504 
Added some special handling for "zero" values.
More details in the comments.

Fix: readResourceData does not work for bool or *bool fields

---

env0/resource_environment.go
env0/resource_environment_test.go

1. create the following configuration:
```tf
terraform {
required_providers {
env0 = {
source  = "env0/env0"
version = "1.2.4"
}
}
}
resource "env0_environment" "aws-development-vault-elb-coralogix-s3-lambda" {
name                       = "aws-development-vault-elb-coralogix-s3-lambda"
project_id                 = "2e8094c9-8771-475e-83a0-23ce1999479e"
approve_plan_automatically = true
workspace                  = "aws-development-vault-elb-coralogix-s3-lambda"
force_destroy              = true
without_template_settings {
repository        = "https://github.com/env0/templates"
path              = "misc/null-resource"
type              = "terraform"
terraform_version = "1.2.9"
}
}
```
2. do `tf init` and `tf …

Fix: tf apply fails when switching from v1.2.4 to v1.2.5

---

tests/integration/006_aws_credentials/main.tf
tests/integration/008_cloud_credentials_project_assignment/main.tf
tests/integration/023_cost_credentials_project_assignment/main.tf
tests/integration/024_cloud_credentials/main.tf

fixes https://github.com/env0/terraform-provider-env0/issues/513
remove white space from every value assign to `External id`

Fix: externalID-white-spaces

---

env0/resource_environment.go
env0/resource_environment_test.go

Fixes #459 
Maintains ordering of state as much as possible (vs the order returned by the API).
Added and updated acceptance tests accordingly.

Fix: lexicographical sorting of configuration items

---

client/template.go
env0/resource_template.go
env0/resource_template_test.go

closes #547 
1. Added the new field.
Note: integration test not added. I could add the integration test if there is an existing template in the test account.

Feat: add support for Azure DevOps templates

---

client/project_policy.go
env0/resource_project_policy.go
env0/resource_project_policy_test.go

fixes #549 
The acceptance test was crashing, and therefore it never ran successfully (and was hiding the bug).
Once I fixed the test I saw a couple of problems. I fixed them.
This should now work as expected.

Fix: "Infinite" isn't a valid value for the max/default TTL Policies API

---

client/api_client.go
client/custom_flow.go
client/custom_flow_test.go

Part of the effort is to add custom-flow support #550.
In this PR I added API client support for CRUD operations on custom flows.
Unit tests were added as well.

Feat: custom flow support

---

examples/resources/env0_agent_project_assignment/resource.tf

The example was missing a name.

Fix env0_agent_project_assignment resource example

---

client/environment.go

Part of subenvironment support effort #536.
In this PR I made some simple struct changes.

Feat: add support for subenvironments

---

.github/workflows/ci.yml
env0/provider.go
tests/harness.go

resolves #568 
Passing an environment variable via the integration tests pipeline.
If the environment variable is set - retry on 404 as well.

Feat: retry on 404 errors on harness testing

---

client/environment.go
env0/resource_project.go
env0/resource_project_test.go
tests/integration/012_environment/main.tf
tests/integration/013_downstream_environments/main.tf
tests/integration/014_environment_scheduling/main.tf

resolves #530 
1. Added a waiting mechanism when destroying a project.
2. updated integration tests to use "wait" instead of "force_destroy".
3. added acceptance tests.

Feat: wait for environment to be destroyed

---

env0/data_api_key.go
env0/data_api_key_test.go
env0/resource_api_key.go
env0/resource_api_key_test.go

resolves #581 
1. added api_key_id to resource and data schemas.
2. updated acceptance tests.

Feat: env0_api_key resource and data source don't store apiKeyId

---

client/template.go
env0/data_environment.go
env0/data_environment_test.go
env0/data_template.go

resolves #586 
1. Added data fields in environment schema.

Feat: add new integrated vcs info to env0_environment data source

---

env0/resource_organization_policy.go
env0/resource_organization_policy_test.go
env0/resource_project_policy.go
env0/resource_project_policy_test.go
env0/utils.go
env0/utils_test.go
env0/validators.go
tests/integration/001_organization/main.tf
tests/integration/011_policy/main.tf
tests/integration/025_notifications/main.tf

resolves #572 
1. Updated both resources `env0_organization_policy` and `env0_project_policy` to support custom TTL values.
2. updated acceptance tests.
3. added conversion functions and unit tests.
4. updated integration tests.

Feat: custom project and organization TTL policy

---

client/project.go
env0/data_project.go
env0/data_project_test.go
env0/resource_project.go
env0/resource_project_test.go
tests/integration/002_project/main.tf

resolves #597 
1. Added a new field to data and resource.
3. Updated integration tests.
4. update go.mod and go.sum due to a security issue.

Feat: add support for Sub Projects to Project data and resource

---

env0/resource_aws_credentials.go
env0/resource_cost_credentials.go

Related to #593.
For now just a deprecation message.

Chore: deprecate 'external_id'

---

tests/integration/012_environment/main.tf

fixes https://github.com/env0/terraform-provider-env0/issues/612
add the random string suffix like for other templates

Chore: make template name unique in workflow environment integration tests

---

env0/resource_project.go
env0/resource_project_test.go

fixes #637 
Removed use-case and test.

Fix: do not fail on 'failed destroyed' environments when removing a project

---

client/environment.go

resolves #641 
Added Error field to the struct.

Feat: add error property in latestDeploymentLog

---

tests/integration/012_environment/main.tf

We want to prevent creating sub environments with the same workspace name and template name but since we can't explicitly set workspace name in the sub environment resource
have a workflow template with a single environment

Fix: Workflow environment creation integration test

---

client/template.go
env0/resource_template.go
env0/resource_template_test.go
tests/integration/004_template/main.tf

resolves #655 
1. Updated API structs.
2. Added required fields in the schema.
3. Added unit tests.
4. Added integration tests.

Feat: helm template support + helm repo vcs option support

---

tests/harness.go

resolves #657 
Tests are now running in parallel. Time is reduced from ~10+ minutes to ~3 minutes

Feat: run harness tests in parallel

---

tests/harness.go

Reverts env0/terraform-provider-env0#669
we have integration tests that search for all the existing templates (022) / teams (021) and it found entities from other test while they being destroyed (deleted) which causes a race condition.

Revert "Feat: run harness tests in parallel"

---

client/api_client.go
client/api_client_mock.go
client/team_environment_assignment.go
client/team_environment_assignment_test.go
env0/provider.go
env0/resource_team_environment_assignment.go
env0/resource_team_environment_assignment_test.go
examples/resources/env0_team_environment_assignment/resource.tf
examples/resources/env0_workflow_triggers copy/resource.tf
tests/integration/012_environment/main.tf

resolves #654 
1. Added new API calls.
2. Added unit tests for API calls.
3. Created a new team environment assignment resource.
4. Added acceptance tests.
5. Added examples.
6. Added integration tests.

Feat: environment Role assignments for Team

---

env0/resource_user_team_assignment.go
env0/resource_user_team_assignment_test.go
env0/utils.go
env0/utils_test.go

fixes #681 
Some user ids have an "_". Original solution assumed it's not possible.
1. created a custom split called lastSplit: split by the last underscore.
2. use lastSplit instead of using strings.Split().
3. Updated the acceptance tests to cover this use-case.
4. Added unit tests for lastSplit.

Fix: cannot create env0_user_team_assignment: validation error

---

env0/resource_custom_flow.go

UI does not render custom flow when a custom name is given. 
The custom flow must match the following format:  `project-<project.id>`
Include a note in the terraform provider resource name field

Chore: add a description note for resource custom_flow name field

---

tests/harness.go

closes #688 
Set provider log mode to "info".

Chore: harness tests don't show expected 'integration tests' mode logs

---

client/http/client.go

fixes #690 
resty does not play nice with non-struct values.
had to manually handle the string pointer use-case.

Fix: env0_agent_values data source doesn't fetch values

---

env0/resource_template.go
env0/resource_template_test.go
tests/integration/004_template/expected_outputs.json
tests/integration/004_template/main.tf

fixes #699 
Keeping the state with "/" to avoid endless drift. Ignoring the value returned by the template if only "/" was omitted.
Added an acceptance test for this use-case and updated the integration test.

Fix: 'endless drift' when setting template path to start with '/'

---

client/template.go
env0/resource_template.go
env0/resource_template_test.go

fixes #659 
1. added omitempty and emptied terraform version if the template type is not "terraform" or "terragrunt".
2. tests updated accordingly.

Fix: do not send terraformVersion unused field

---

client/http/errors.go
env0/resource_environment.go
env0/resource_environment_test.go

fixes #704 
1. On 400 error, prints a warning, but does not fail the destroy.
2. Updated acceptance tests to cover this use case.

Fix: destroy already destroyed workflow environment fails with error

---

client/git_token.go
env0/resource_git_token_test.go

fixes #707 
1. "value" returns *****. Therefore, it causes a drift.
2. It is now ignored (except for creation).

Fix: env0_git_token recreating in every tf apply

---

.terraform-registry

Since we published a bad version (1.14.15) we want to remove from the registry, the Terraform Registry product team require proof that this request is authentic, and have asked for this file with the following content. 
@TomerHeber please verify that I got the version number right :)

Chore: Create .terraform-registry with delete request for bad version

---

tests/integration/025_notifications/expected_outputs.json
tests/integration/025_notifications/main.tf

test `025_notifications` uses `all_notifications`, and it fetches data from other tests, such as `017_notification`, that may become unavailable during test 025's run.
make the test rely solely on its own data
ran the test locally to make sure it works on its own. deliberately failing it is much harder, didn't happen sporadically (that we caught) until a few days prior to the PR

Fix: integration test 025 is not isolated

---

env0/provider.go
env0/provider_test.go

resolves #738 
1. API key and API secret are now optional in the schema.
2. Will still return an error if they're not configured via schema or environment variables.
3. Minor updates to provider documentation to make it clearer.

Feat: clarify provider documentation

---

env0/data_environment.go
env0/data_environment_test.go
env0/resource_environment.go

resolves #737 
1. Updated the schema to make project_id optional and not just computed.
2. Added an acceptance test for the new use-case. (Failed before adding code, passed updating code).
3. Updated code to filter out if project_id is set.

Feat: env0_environment with project_id property

---

env0/provider.go

Chore: modify provider documentation for api_key and api_secret

---

client/environment.go
env0/resource_custom_role.go
env0/resource_environment.go
env0/resource_environment_test.go

resolves #761 
1. Added the schema and implemented the requirements.
2. Added additional acceptance tests.

Feat: support 'Enable Remote Apply' flag on environment settings

---

env0/resource_environment.go
env0/resource_environment_test.go

resolves #766 
1. Removed forcenew when template id is changed.
2. Return an error if template id is set, and is then modified.
3. Add an acceptance test to validate that the plan will fail.

Feat: cannot change template id, instead return an error

---

client/module.go
env0/resource_module.go
env0/resource_module_test.go
tests/integration/018_module/main.tf

resolves #775 
1. Updated the module schema.
2. Updated the module API structs.
3. Updated the module acceptance tests.
4. Updated the module integration tests.

Feat: support tagPrefix on modules

---

client/template.go
env0/resource_environment.go
env0/resource_environment_test.go
env0/resource_template.go
env0/resource_template_test.go

resolves #784 
1. Updated the schema.
2. Added special handling to support the unique behavior.
3. Updated acceptance tests.

Feat: add support for running terragrunt with opentofu

---

client/project.go
env0/data_project.go
env0/data_projects.go
env0/data_projects_test.go
env0/provider.go
examples/data-sources/env0_projects/data-source.tf
tests/integration/002_project/main.tf

resolves #786 
1. Added the new data-source.
2. Added acceptance tests.
3. Updated integration tests.
4. Added an example.

Feat: add env0_projects (plural) data resource

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
client/module.go
env0/resource_module.go
env0/resource_module_test.go
env0/resource_template.go
env0/validators.go
tests/integration/018_module/main.tf

resolves #788 
1. Added the new fields to the API structs.
2. Added the new fields to the schema.
3. Added a condition to fail module test is disabled but opentofu or run_tests_on pull are enalbed.
4. Updated integration tests.
5. Updated acceptance tests.

Feat: module testing support

---

client/environment.go
env0/resource_environment.go
env0/resource_environment_test.go

we want to support the new `prevent_auto_deploy` argument of the create envirionment API.
using the property, the user can skip the deployment of the environment in env0 and only create it on resource create. updating and destroying should remain the same
- add support for the new `prevent_auto_deploy` api

Feat: add `prevent_auto_deploy` flag to create without deploy

---

client/api_client.go
client/api_client_mock.go
client/team_organization_assignment.go
client/team_organization_assignment_test.go
env0/provider.go
env0/resource_team_organization_assignment.go
env0/resource_team_organization_assignment_test.go
examples/resources/env0_team_organization_assignment/resource.tf
tests/integration/009_team/main.tf

resolves #807 
1. Added  API calls.
2. Added unit tests for API calls.
3. Created a new resource.
4. Added acceptance tests for the new resource.
5. Added integration test for the resource.
6. Added examples.

Feat: Organization Role assignments for Team

---

client/api_client.go
client/api_client_mock.go
client/team_project_assignment.go
client/team_project_assignment_test.go
env0/resource_team_project_assignment.go
env0/resource_team_project_assignment_test.go

Part of #817. Will create another PR for refactoring the API.
1. Modifed the API code.
2. Updated unit tests.
3. Modified the resource code to use the new API.
4. Updated acceptance tests.

Feat: Refactor for Project Role assignments for Team

---

client/environment.go
env0/resource_environment.go
env0/resource_environment_test.go

resolves #826 
1. Added the k8s_namespace to the schema and API structures.

Feat: add support for namespace in env0_environment resource

---

client/api_client.go
client/api_client_mock.go
client/kubernetes_credentials.go
client/kubernetes_credentials_test.go
env0/credentials.go
env0/provider.go
env0/resource_kubeconfig_credentials.go
env0/resource_kubeconfig_credentials_test.go
tests/integration/024_cloud_credentials/main.tf

part 1 of of #837. Adding support for kubeconfig (1 out of 4).
1. Added a new API for creating kubernetes credential types.
2. Added some enums, constants and structs for the new types.
3. Added a test for the new API.
4. Added a new resource for kube config.
5. Added tests for the new resource.
6. Added a kube config use-case to the integration tests.

Feat: Add Support for K8s Credentials - kubeconfig

---

client/api_client.go
client/api_client_mock.go
client/kubernetes_credentials.go
client/kubernetes_credentials_test.go
env0/provider.go
env0/resource_aws_eks_credentials.go
env0/resource_aws_eks_credentials_test.go
env0/resource_azure_aks_credentials.go
env0/resource_azure_aks_credentials_test.go
env0/resource_gcp_gke_credentials.go
env0/resource_gcp_gke_credentials_test.go
env0/resource_kubeconfig_credentials.go
env0/resource_kubeconfig_credentials_test.go
tests/integration/024_cloud_credentials/main.tf

resolves #837 
Part 2 (in part 1 only 1 kubernetes credentials was added).
1. Add  the 3 other kubernetes credentials resources.
2. Add acceptance tests.
3. Add integration tests.

Feat: add Support for K8s Credentials

---

env0/data_sshkey.go
env0/data_sshkey_test.go
go.mod
go.sum

resolves #848 
1. Added a backoff library.
2. Added backoff for getSshKeyByName.
3. Added an acceptance test.

Feat: add a retry mechanism for getSshKeyByName

---

client/api_client.go
client/api_client_mock.go
client/configuration_set.go
client/configuration_set_test.go
client/configuration_variable.go

Part of #829
1. Added the API calls required for configuration set.
2. Added unit tests for configuration set.

Feat: add API calls for configuration set

---

client/api_client.go
client/api_client_mock.go
client/environment_import.go
client/environment_import_test.go

part of https://github.com/env0/terraform-provider-env0/issues/856
Add environment import CRUD to api client

Chore: add environment import api client

---

client/api_client.go
client/api_client_mock.go
client/configuration_set_assignment.go
client/configuration_set_assignment_test.go
env0/provider.go
env0/resource_variable_set_assignment.go
env0/resource_variable_set_assignment_test.go
examples/resources/env0_variable_set/resource.tf
tests/integration/004_template/main.tf
tests/integration/033_variable_set/main.tf

Part of #829 
1. Added the assignment resource.
2. Added an API call.
3. Added unit tests.
4. Added acceptance tests.
5. Added integration tests.
6. Updated examples.

Feat: add support for variable set assignment resource

---

env0/resource_environment.go
env0/resource_environment_test.go

fixes #873 
Modifed scope from workflow to environment (for a sub environment). Updated test accordingly.

Fix: removing configuration from sub_environment_configuration

---

client/configuration_set_assignment.go
client/environment.go
env0/data_environment.go
env0/resource_environment.go
env0/resource_environment_test.go
tests/integration/012_environment/main.tf

resolves #829 
1. Added 'variable_sets' to the schema (a list of ids).
2. Implemented handling in environment resource for "read, update and create".
3. Added an acceptance test.
4. Update an integration test to cover the use-case.

Feat: add variable set support for environment schema

---

tests/integration/013_downstream_environments/main.tf
tests/integration/014_environment_scheduling/main.tf

[fixes](https://github.com/env0/terraform-provider-env0/issues/881)
We noticed two of the integration tests are flaky. It is caused by environments being deployed again just before we try to destroy the project
since this is not the focus of the test, we decided to force destroy the project when it ends.

Fix: add force destroy project to flaky tests

---

tests/integration/003_configuration_variable/main.tf
tests/integration/029_provider/main.tf

fixes #877 
Discussed in:  https://env0.slack.com/archives/C01QBBEGBEH/p1719272417817659
Decided to add a sleep to the test itself - this should avoid eventual consistency issues (will add longer sleep if needed).

Fix: fix 029_provider flaky test by adding sleep

---

client/configuration_set.go
env0/resource_environment.go
env0/resource_environment_test.go
env0/resource_variable_set_assignment.go
env0/resource_variable_set_assignment_test.go

fixes #888 
fixes #894 
fixes #895 
1. Fixed conflicts between environment sets and non-environment sets.
2. Filter out scopes assigned implicitly.
3. Updated tests.
4. Updated documentation to warn about conflicts.

Fix: drift issues with variable sets

---

client/project_policy.go
env0/resource_configuration_variable_test.go
env0/resource_project_policy.go
env0/resource_project_policy_test.go
tests/integration/011_policy/main.tf

resolves #891 
1. Added the new field to the schema and API calls.
3. Updated harness tests.

Feat: add env0_project_policy option for Environment Output

---

docs/resources/environment.md
env0/resource_environment.go

Right now the description of variable_sets` of the environment resource is unclear, and does not mention that this should contain the IDs of the variable sets
Adapt the description

Chore: Change description of `variable_sets` field on environment_resource

---

client/template.go
env0/data_template.go
env0/data_template_test.go

resolves #902 
1. Added token_name to template data-source schema.
2. Updated the structs.
3. Updated the acceptance tests.

Feat: add token_name as a field for data env0_template

---

env0/resource_module.go

* module_provider was marked as optional
* module_provider now marked as required

Chore: make module_provider required

---

client/api_client.go
client/api_client_mock.go
client/configuration_set.go
client/configuration_set_test.go
env0/data_variable_set.go
env0/data_variable_set_test.go
env0/provider.go
env0/resource_team_organization_assignment.go
examples/data-sources/env0_variable_set/data-source.tf
tests/integration/033_variable_set/main.tf

resolves #892 
1. Added the new data resource.
2. Added a required API call.
3. Added unit tests for the new API call.
4. Added acceptance tests for the new data source.
5. Added a couple of harness tests.
6. Added examples.

Feat: add data source for env0_variable_set

---

client/template.go
client/template_test.go
env0/data_template.go
env0/data_template_test.go
env0/resource_template.go
env0/resource_template_test.go
env0/test_helpers.go
tests/integration/004_template/main.tf

resolves #926 
1. Updated the template API structs.
2. Updated the schema and implemented support.
3. Updated acceptance tests.
4. Added a harness test.
5. Some other misc changes (part of linting/bug fixes effort).

Feat: support new ansible template type

---

client/api_client.go
client/api_client_mock.go
client/environment.go
client/environment_test.go
env0/resource_environment.go
env0/resource_environment_test.go
tests/integration/012_environment/main.tf

resolves #938 
1. Added a new API call for moving environments.
2. Added a unit test for the new API call.
3. Removed 'forceNew' from 'project_id' in the environment schema.
4. On environment update, if project_id is updated, call the move API.
5. Added an acceptance tests.
6. Updated harness tests.

Feat: add support for 'move environment' backend

---

client/environment.go
env0/resource_environment.go
env0/resource_environment_test.go
env0/utils.go

resolves #942 
1. Added `isRemoteApplyEnabled` to the create structs.
2. Updated schema text.
3. Added a new test.

Feat: is_remote_apply_enabled not being sent to BE

---

env0/resource_environment.go
env0/resource_environment_test.go

fixes #951 
Creating an 'inactive' account should be blocked (not supported).
1. Updated the documents.
2. Fail this use-case.
3. Added an acceptance test.

Fix: fail when trying to create an in_active environment

---

env0/provider.go
env0/provider_test.go

fixes #949 
Removed the default error handler.

Fix: do not retry for 4xx errors

---

env0/resource_environment.go
env0/resource_environment_test.go
tests/integration/012_environment/main.tf

fixes #947 
1. For workflow - always pass `RequiredUserApproval` as `false` in the deploy payload (for the root env).
3. Updated harness tests.

Fix: approve_plan_automatically attribute fails for sub_environment

---

env0/resource_custom_role.go

missing:
MOVE/IMPORT_ENVIRONMENTS
we're missing 2 allowed values in a custom role
add them

Chore: missing permissions for custom role

---

tests/integration/004_template/main.tf
tests/integration/012_environment/main.tf

A change on env0's API requires to enforce the `terraform_tf_binary` when `terraform_version` is specified.
Fixes #975
Enforce `terraform_tf_binary`

fix: integration tests templates must enforce terraform_tf_binary
